name: Push a NuGet package to Azure Artifacts or GitHub Package Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_ARTIFACTS_FEED_URL: https://avid29.pkgs.visualstudio.com/ClusterF_ck/_packaging/ClusterF_ck/nuget/v3/index.json  
  TEST_BUILD_CONFIGURATION: 'Debug'    # This build configuration is used for testing
  PACK_BUILD_CONFIGURATION: 'Release'  # This build configuration is used for packing and publishing
  DOTNET_VERSION: '6.x' 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and package
      - name: dotnet build and test
        run: |
          dotnet restore
          dotnet build --configuration '${{ env.TEST_BUILD_CONFIGURATION }}'
          dotnet test --configuration '${{ env.TEST_BUILD_CONFIGURATION }}'

  pack-and-publish:
    if: ${{github.event_name == 'push'}}
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }} 

      # Run dotnet build and package
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration '${{ env.PACK_BUILD_CONFIGURATION }}'
          dotnet pack -c '${{ env.PACK_BUILD_CONFIGURATION }}' --version-suffix $GITHUB_RUN_ID --output ./artifacts

      # Publish the package to Azure Artifacts
      - name: 'dotnet publish'
        run: dotnet nuget push --api-key AzureArtifacts ./artifacts/*.nupkg --skip-duplicates
