# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test and Publish

on:
  # Triggers the workflow when a pull request is made to the main branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    # Run the workflow on ubuntu
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Loads dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build solution
    - name: Build
      run: dotnet build --no-restore

    # Run tests
    - name: Test
      run: dotnet test --no-build --verbosity normal

  # Publish the packages to Azure DevOps
  publish-nightlies-azure-devops:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nuget_packages
        path: artifacts
    - uses: actions/setup-dotnet@v3
      with:
        source-url: "https://avid29.pkgs.visualstudio.com/ClusterF_ck/_packaging/ClusterF_ck/nuget/v3/index.json"
    - run: dotnet nuget push "artifacts\*.nupkg" --api-key AzureDevOps --skip-duplicate
